---
# package manage
- name: Install a specific version of rsyslog
  yum:
    name: "{{ pkg_version }}"
    state: "{{ pkg_state }}"

# config manage
- name: Create config backup dir
  file:
    path: /etc/backup
    state: directory
    mode: 0755

- name: Backup config before overwrite it on target host.
  synchronize:
    src: /etc/rsyslog.d
    dest: /etc/backup/
  delegate_to: "{{ inventory_hostname }}"

- name: Synchronize files in dest on the remote host.
  synchronize:
    src: "etc/rsyslog.d"
    dest: "/etc/"
    delete: yes
    recursive: yes
  notify:
    - restart rsyslog

# log manage
- name: Rotate rsyslog-stats with logrotate
  lineinfile:
    dest: "/etc/logrotate.d/syslog"
    insertbefore: "BOF"
    line: "/var/log/rsyslog-stats"

- name: Add line into logrotate.d/syslog to rotate syslog properly
  lineinfile:
    dest: "/etc/logrotate.d/syslog"
    insertafter: "(.*)/bin/kill(.*)"
    line: "        /bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true"

# service manage
- name: Start/stop rsyslog service
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"

# vim: sw=2 ft=ansible
